* El texto expositivo

** Introducción
Nos informa con objetividad y claridad aquellos aspectos que nos interesan del mundo que nos rodea y de cualquier área del conocimiento que nos interesa.

** Tiene una función referencial
Es la función que le damos a la lengua cuando queremos hablar de sucesos reales; es decir, hechos, datos y explicaciones, tal como son.

Ofrece al lector una información explícita sobre un tema puntual, de manera objetiva, sin que medie en ningún momento la opinión del autor o sus posicionamientos respecto al tema. En consecuencia tampoco necesita utilizar argumentaciones para convencer.

** Tipos de textos expositivos
*** De divulgación 
Dirigido a un público amplio, sin requerimientos especializados. Abordan temas de interés general, usualmente de una forma simple y accesible.

*** Especializados
Dirigido a un público reducido y especializado, por lo que se manejan en un lenguaje técnico.

** Finalidades del Texto Expositivo
Informar con: 
Rigor
Confianza 
Objetividad:
Subjetividad: se basa en la percepción del emisor, en cómo lo siente él.
Objetividad: se basa en datos para informar sobre el tema
Precisión:
Claridad
** Estructura de los textos expositivos
*** Introducción
Describe:
¿Qué?
¿Por qué? y ¿Para qué?
¿Cómo?
*** Desarrollo
El cuerpo del texto en donde se lleva la exposición de la información clara y organizada. Es la parte central, organizada por párrafos y capítulos
*** Conclusión
Se resumen los aspectos fundamentales del tema y se recapitula o hace una breve síntesis de lo dicho.
** Otros recursos
Definiciones: Son necesarias para hacer más precisos el texto y el desarrollo de la exposición.
Ejemplos: Para que el receptor comprenda mejor lo que lee
Símbolos gráficos
